### ISSUE TITLE
Doc incorrect / dead link

### ISSUE THREAD

**Issue by CollinChaffin** [nZEDb/nZEDbPre_Dumps#2]
The script listed in 0readme.md here as the method to assemble these daily dumps into a usable db
````
https://github.com/nZEDb/nZEDb/blob/master/cli/data/predb_import_daily_batch.php
````

is a 404 not found so right now it's virtually impossible to have this system working.  All the other docs and scripts still link to the now non-existent cancelled dropbox account, so that too should really be updated as the questions fly daily now about it.

There has got to be an easier way to store and distribute these predb dumps.  Can't we simply store one large seed db at least through 1st of last calendar month tarred and then roll it with the handful of dailies?  These are really not that large being gzipped and tarred being simple csv text.

**Comment by Wally73** [comment]
just look at 

https://github.com/nZEDb/nZEDb/blob/0.x/cli/data/predb_import_daily_batch.php 

(fixed the url to the right script) 

dailies aren't the old dropbox one btw

**Comment by wimjan123** [comment]
Where can we find the old dropbox ones?
